name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    # GitHub ActionsでAndroidエミュレータを高速に動作させるためには macOS ランナーが推奨されています
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Remove strict JVM daemon properties to use setup-java JDK
      run: rm -f gradle/gradle-daemon-jvm.properties

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest -Porg.gradle.java.installations.auto-download=false

    - name: AVD cache
      uses: actions/cache@v5
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-36

    - name: Create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 36
        target: google_apis
        arch: arm64-v8a
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: Run Instrumented Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 36
        target: google_apis
        arch: arm64-v8a
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew connectedAndroidTest -Porg.gradle.java.installations.auto-download=false
